// ⚠️ FICHIER AUTO-GÉNÉRÉ — ne pas modifier manuellement
// Modifie CLIENT.md puis relance : npm run sync-client

export const clientConfig = {
  identity: {
    prenomDirigeant: "Marc",
    nomDirigeant: "Durand",
    nomEntreprise: "Durand Plomberie",
    nomLegal: "Durand Plomberie SARL",
    genreDirigeant: "masculin",
    founder: "Marc Durand",
  },
  contact: {
    telephone: "06 72 45 89 13",
    telephoneHref: "tel:+33672458913",
    telephoneUrgence: "06 72 45 89 13",
    email: "contact@durand-plomberie.fr",
    adresse: "14 rue des Ateliers",
    ville: "Lyon",
    codePostal: "69003",
    departement: "Rhône",
    region: "Auvergne-Rhône-Alpes",
    zoneIntervention: "Lyon et 30km autour",
    zoneKm: "30",
  },
  horaires: {
    semaine: "7h - 20h",
    samedi: "8h - 18h",
    dimanche: "Fermé",
    urgence: "24h/24 - 7j/7",
  },
  branding: {
    couleurPrimaireHue: "245",
    couleurAccentHue: "44",
  },
  social: {
    facebook: "https://facebook.com/durand-plomberie-lyon",
    instagram: "https://instagram.com/durandplomberie",
    google: "https://g.page/durand-plomberie-lyon",
  },
  domaine: "durand-plomberie-lyon.fr",
  url: "https://www.durand-plomberie-lyon.fr",
  legal: {
    siret: "912 345 678 00012",
    rge: "RGE QualiPAC n°12345",
    assuranceDecennale: "AXA - Police n°789456123",
  },
  chiffres: {
    anneesExperience: 15,
    nombreInterventions: 3500,
    noteGoogle: 4.8,
    nombreAvis: 127,
    anneeCreation: 2011,
    delaiIntervention: "2h",
    disponibilite: "7j/7",
    tauxSatisfaction: "98",
  },
  geo: {
    latitude: "45.7640",
    longitude: "4.8357",
  },
  communes: [
    { name: "Lyon", postalCode: "69001-69009" },
    { name: "Villeurbanne", postalCode: "69100" },
    { name: "Caluire-et-Cuire", postalCode: "69300" },
    { name: "Bron", postalCode: "69500" },
    { name: "Vénissieux", postalCode: "69200" },
    { name: "Saint-Priest", postalCode: "69800" },
    { name: "Vaulx-en-Velin", postalCode: "69120" },
    { name: "Tassin-la-Demi-Lune", postalCode: "69160" },
    { name: "Écully", postalCode: "69130" },
    { name: "Oullins", postalCode: "69600" },
    { name: "Sainte-Foy-les-Lyon", postalCode: "69110" },
    { name: "Rillieux-la-Pape", postalCode: "69140" },
    { name: "Décines-Charpieu", postalCode: "69150" },
    { name: "Meyzieu", postalCode: "69330" },
    { name: "Francheville", postalCode: "69340" },
    { name: "Saint-Genis-Laval", postalCode: "69230" },
    { name: "Chassieu", postalCode: "69680" },
    { name: "Craponne", postalCode: "69290" },
  ],
  services: [
    { title: "Dépannage urgent", shortDescription: "Intervention rapide en moins de 2h pour toutes vos urgences plomberie.", description: "Fuite d'eau, canalisation bouchée, dégât des eaux, panne de chaudière... Notre équipe intervient en urgence 7j/7 dans un rayon de 30 km autour de Lyon. Diagnostic sur place et réparation immédiate dans la majorité des cas.", icon: "Siren", slug: "/depannage-plomberie" },
    { title: "Plomberie générale", shortDescription: "Installation, remplacement et mise aux normes de vos équipements.", description: "Robinetterie, tuyauterie, raccordements, WC, éviers, recherche de fuite... Nous intervenons pour tous vos travaux de plomberie, de l'installation neuve à la mise aux normes de vos installations existantes.", icon: "Wrench", slug: "/plomberie" },
    { title: "Salle de bain", shortDescription: "Rénovation complète, douche italienne, adaptation PMR.", description: "De la conception à la réalisation, nous prenons en charge votre projet de rénovation de salle de bain. Douche italienne, remplacement baignoire, accessibilité PMR, meuble vasque... Un interlocuteur unique du début à la fin.", icon: "Bath", slug: "/renovation-salle-de-bain" },
    { title: "Chauffage", shortDescription: "Chaudière, pompe à chaleur, plancher chauffant, entretien annuel.", description: "Installation et remplacement de chaudière gaz condensation, pompe à chaleur air-eau, plancher chauffant, radiateurs. Entretien annuel obligatoire et dépannage de votre système de chauffage.", icon: "Flame", slug: "/chauffage" },
    { title: "Chauffe-eau", shortDescription: "Remplacement, ballon thermodynamique, détartrage.", description: "Remplacement de chauffe-eau électrique ou gaz, installation de ballon thermodynamique pour réduire votre facture énergétique. Détartrage et entretien pour prolonger la durée de vie de votre équipement.", icon: "Droplets", slug: "/chauffe-eau" },
    { title: "Entretien", shortDescription: "Contrats d'entretien chaudière et maintenance préventive.", description: "L'entretien annuel de votre chaudière est obligatoire. Nous proposons des contrats d'entretien incluant la visite annuelle, le dépannage prioritaire et les pièces d'usure.", icon: "ClipboardCheck", slug: "/chauffage#entretien" },
  ],
  testimonials: [
    { name: "Sophie L.", rating: 5, text: "Intervention rapide pour une fuite sous l'évier. Le plombier est arrivé en 45 minutes, très professionnel et propre. Réparation faite en moins d'une heure. Je recommande vivement !", date: "Janvier 2026", source: "Google" },
    { name: "Philippe M.", rating: 5, text: "Rénovation complète de notre salle de bain. Le résultat est magnifique, exactement ce qu'on voulait. L'équipe a été ponctuelle et le chantier toujours propre. Le devis a été respecté au centime près.", date: "Décembre 2025", source: "Google" },
    { name: "Marie-Claire D.", rating: 5, text: "Remplacement de notre vieille chaudière par une pompe à chaleur. Très bon conseil sur les aides disponibles, accompagnement dans les démarches. On a déjà vu la différence sur la facture de chauffage.", date: "Novembre 2025", source: "Google" },
    { name: "Jean-Pierre R.", rating: 4, text: "Bonne intervention pour un WC bouché un dimanche matin. Le tarif week-end était annoncé clairement dès le téléphone. Travail rapide et efficace.", date: "Octobre 2025", source: "Google" },
    { name: "Isabelle T.", rating: 5, text: "On a fait appel à Durand Plomberie pour installer notre douche italienne. Le travail est impeccable, les finitions soignées. Marc est de bon conseil et très à l'écoute.", date: "Septembre 2025", source: "Google" },
    { name: "Laurent G.", rating: 5, text: "Entretien annuel de la chaudière effectué dans les règles. Le technicien a pris le temps d'expliquer les points de contrôle et m'a donné des conseils pour optimiser la consommation.", date: "Août 2025", source: "Google" },
    { name: "Catherine B.", rating: 5, text: "Installation d'un chauffe-eau thermodynamique. Très satisfaite du résultat, l'équipe a été très professionnelle. Le devis détaillé nous a rassurés avant de nous lancer.", date: "Juillet 2025", source: "Google" },
    { name: "Nicolas F.", rating: 4, text: "Dépannage rapide pour une fuite sur un radiateur. L'intervention a été propre et le prix raisonnable. Seul bémol, un peu de retard à l'arrivée mais prévenu par téléphone.", date: "Juin 2025", source: "Google" },
    { name: "Véronique P.", rating: 5, text: "Rénovation de notre salle de bain pour adaptation PMR pour ma mère. Marc a été d'une grande aide pour choisir les équipements adaptés. Travail soigné et respectueux.", date: "Mai 2025", source: "Google" },
    { name: "Frédéric A.", rating: 5, text: "Installation complète de la plomberie dans notre maison neuve. Tout fonctionne parfaitement, aucun problème depuis un an. Rapport qualité-prix excellent.", date: "Avril 2025", source: "Google" },
  ],
  admin: {
    password: "1234",
  },
  seo: {
    metaTitleAccueil: "Plombier Lyon — Durand Plomberie | Dépannage 7j/7",
    metaDescAccueil: "Plombier chauffagiste à Lyon. Dépannage urgent 7j/7, installation, rénovation salle de bain, chauffage. Devis gratuit.",
    descriptionEntreprise: "Plombier chauffagiste à Lyon. Dépannage urgent 7j/7, installation, rénovation salle de bain, chauffage. Devis gratuit.",
    slogan: "Votre plombier à Lyon — Dépannage 7j/7, intervention rapide",
  },
} as const;

export type ClientConfig = typeof clientConfig;
